server:
  port: 8081
spring:
  application:
    name: conversion
  # 数据源
  datasource:
    dynamic:
      primary: ms187
      datasource:
        ms187:
          username: sa
          password: zhangxueyang@2021
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://192.168.4.187:1433;
#        datasource209:
#          username: test
#          password: wlzx87811024
#          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#          url: jdbc:sqlserver://192.168.0.209:1433;
        ms210:
          username: sa
          password: wlzx@87811024
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://172.16.5.74:1433;

      druid: #以下均为默认值
        initial-size: 3
        max-active: 8
        min-idle: 2
        max-wait: -1
        min-evictable-idle-time-millis: 30000
        max-evictable-idle-time-millis: 30000
        time-between-eviction-runs-millis: 0
        validation-query: select 1
        validation-query-timeout: -1
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        pool-prepared-statements: true
        max-open-prepared-statements: 100
        filters: stat,wall
        share-prepared-statements: true
logging:
  level:
    root: INFO
    org:
      hibernate: INFO
    com:
      itmuch: DEBUG
    org.hibernate.type.descriptor.sql:
      BasicBinder: TRACE
      BasicExtractor: TRACE
  #    com.yq.conversion.dao: debug
  config: classpath:logback-spring.xml
mybatis:
  configuration:
    jdbc-type-for-null: null
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
