
package cn.andy.AndyWeb.service;

import cn.andy.AndyWeb.entity.FailMessage;
import cn.andy.AndyWeb.entity.ObjectFactory;
import cn.andy.AndyWeb.entity.ResKnowledgeAccount;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceKnowAccountService", targetNamespace = "http://webservice.web.csjsite.baosight.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceKnowAccountService {


    /**
     * 
     * @param resKnowledgeAccountList
     * @return
     *     returns com.baosight.csjsite.TestWsdl.FailMessage
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "knowledgeAccountList", targetNamespace = "http://webservice.web.csjsite.baosight.com/", className = "com.baosight.csjsite.TestWsdl.KnowledgeAccountList")
    @ResponseWrapper(localName = "knowledgeAccountListResponse", targetNamespace = "http://webservice.web.csjsite.baosight.com/", className = "com.baosight.csjsite.TestWsdl.KnowledgeAccountListResponse")
    public FailMessage knowledgeAccountList(
            @WebParam(name = "resKnowledgeAccountList", targetNamespace = "")
                    List<ResKnowledgeAccount> resKnowledgeAccountList);

}
