
package cn.andy.AndyWeb.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebServiceKnowledgeServiceImplService", targetNamespace = "http://webservice.web.csjsite.baosight.com/", wsdlLocation = "http://www.yliuy.com/webservice/knowledgeProperty?wsdl")
public class WebServiceKnowledgeServiceImplService
    extends Service
{

    private final static URL WEBSERVICEKNOWLEDGESERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICEKNOWLEDGESERVICEIMPLSERVICE_EXCEPTION;
    private final static QName WEBSERVICEKNOWLEDGESERVICEIMPLSERVICE_QNAME = new QName("http://webservice.web.csjsite.baosight.com/", "WebServiceKnowledgeServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.yliuy.com/webservice/knowledgeProperty?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICEKNOWLEDGESERVICEIMPLSERVICE_WSDL_LOCATION = url;
        WEBSERVICEKNOWLEDGESERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public WebServiceKnowledgeServiceImplService() {
        super(__getWsdlLocation(), WEBSERVICEKNOWLEDGESERVICEIMPLSERVICE_QNAME);
    }

    public WebServiceKnowledgeServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICEKNOWLEDGESERVICEIMPLSERVICE_QNAME, features);
    }

    public WebServiceKnowledgeServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICEKNOWLEDGESERVICEIMPLSERVICE_QNAME);
    }

    public WebServiceKnowledgeServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICEKNOWLEDGESERVICEIMPLSERVICE_QNAME, features);
    }

    public WebServiceKnowledgeServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceKnowledgeServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServiceKnowledgeService
     */
    @WebEndpoint(name = "WebServiceKnowledgeServiceImplPort")
    public WebServiceKnowledgeService getWebServiceKnowledgeServiceImplPort() {
        return super.getPort(new QName("http://webservice.web.csjsite.baosight.com/", "WebServiceKnowledgeServiceImplPort"), WebServiceKnowledgeService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceKnowledgeService
     */
    @WebEndpoint(name = "WebServiceKnowledgeServiceImplPort")
    public WebServiceKnowledgeService getWebServiceKnowledgeServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.web.csjsite.baosight.com/", "WebServiceKnowledgeServiceImplPort"), WebServiceKnowledgeService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICEKNOWLEDGESERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw WEBSERVICEKNOWLEDGESERVICEIMPLSERVICE_EXCEPTION;
        }
        return WEBSERVICEKNOWLEDGESERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
