
package cn.lalisa.web.service;

import cn.lalisa.web.entity.FailMessage;
import cn.lalisa.web.entity.ObjectFactory;
import cn.lalisa.web.entity.ResKnowledgeAgency;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceKnowledgeService", targetNamespace = "http://webservice.web.csjsite.baosight.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceKnowledgeService {


    /**
     * 
     * @param resKnowledgeAgency
     * @return
     *     returns com.baosight.csjsite.TestWsdl.FailMessage
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "knowledgeAgency", targetNamespace = "http://webservice.web.csjsite.baosight.com/", className = "cn.andy.AndyWeb.entity.KnowledgeAgency")
    @ResponseWrapper(localName = "knowledgeAgencyResponse", targetNamespace = "http://webservice.web.csjsite.baosight.com/", className = "cn.andy.AndyWeb.entity.KnowledgeAgencyResponse")
    public FailMessage knowledgeAgency(
            @WebParam(name = "resKnowledgeAgency", targetNamespace = "")
                    ResKnowledgeAgency resKnowledgeAgency);

    /**
     * 
     * @param resKnowledgeAgency
     * @return
     *     returns com.baosight.csjsite.TestWsdl.FailMessage
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "batchKnowledgeAgency", targetNamespace = "http://webservice.web.csjsite.baosight.com/", className = "cn.andy.AndyWeb.entity.BatchKnowledgeAgency")
    @ResponseWrapper(localName = "batchKnowledgeAgencyResponse", targetNamespace = "http://webservice.web.csjsite.baosight.com/", className = "cn.andy.AndyWeb.entity.BatchKnowledgeAgencyResponse")
    public FailMessage batchKnowledgeAgency(
            @WebParam(name = "resKnowledgeAgency", targetNamespace = "")
                    List<ResKnowledgeAgency> resKnowledgeAgency);

}
