
package cn.lalisa.web.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebServiceKnowAccountServiceImplService", targetNamespace = "http://webservice.web.csjsite.baosight.com/", wsdlLocation = "http://119.3.210.47/csjsite-admin/webservice/knowledgeAccount?wsdl")
public class WebServiceKnowAccountServiceImplService
    extends Service
{

    private final static URL WEBSERVICEKNOWACCOUNTSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICEKNOWACCOUNTSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName WEBSERVICEKNOWACCOUNTSERVICEIMPLSERVICE_QNAME = new QName("http://webservice.web.csjsite.baosight.com/", "WebServiceKnowAccountServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://119.3.210.47/csjsite-admin/webservice/knowledgeAccount?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICEKNOWACCOUNTSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        WEBSERVICEKNOWACCOUNTSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public WebServiceKnowAccountServiceImplService() {
        super(__getWsdlLocation(), WEBSERVICEKNOWACCOUNTSERVICEIMPLSERVICE_QNAME);
    }

    public WebServiceKnowAccountServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICEKNOWACCOUNTSERVICEIMPLSERVICE_QNAME, features);
    }

    public WebServiceKnowAccountServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICEKNOWACCOUNTSERVICEIMPLSERVICE_QNAME);
    }

    public WebServiceKnowAccountServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICEKNOWACCOUNTSERVICEIMPLSERVICE_QNAME, features);
    }

    public WebServiceKnowAccountServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceKnowAccountServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServiceKnowAccountService
     */
    @WebEndpoint(name = "WebServiceKnowAccountServiceImplPort")
    public WebServiceKnowAccountService getWebServiceKnowAccountServiceImplPort() {
        return super.getPort(new QName("http://webservice.web.csjsite.baosight.com/", "WebServiceKnowAccountServiceImplPort"), WebServiceKnowAccountService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceKnowAccountService
     */
    @WebEndpoint(name = "WebServiceKnowAccountServiceImplPort")
    public WebServiceKnowAccountService getWebServiceKnowAccountServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.web.csjsite.baosight.com/", "WebServiceKnowAccountServiceImplPort"), WebServiceKnowAccountService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICEKNOWACCOUNTSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw WEBSERVICEKNOWACCOUNTSERVICEIMPLSERVICE_EXCEPTION;
        }
        return WEBSERVICEKNOWACCOUNTSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
